"""The EMITTER (architecture.md): solved rig -> the projection triple,
split by visibility (ontology §3):

  MCU-visible-static   -> .overlay        (joins the unchanged Zephyr build)
  human-realized       -> config sheet    (markdown)
  runtime-discoverable -> expectations    (YAML stub, A6)

Pure rendering under the strong contract: never decides anything, never
fails on an analyzer-accepted rig. Deterministic: all output sorted by
stable keys, independent of rig-file declaration order (R7/R18).

Label policy (R10 is parked; this is the prototype's deterministic scheme):
generated label = <instance>_<shield-local label>, e.g. logger_a_dl_rtc.
"""
from __future__ import annotations

from .analyzer import Solved
from .ctypes_registry import load_types

GEN = "generated by rigexp — do not edit; the rig file is the source of truth (R3)"


def emit(solved: Solved) -> dict[str, str]:
    return {
        "overlay": _overlay(solved),
        "config-sheet.md": _sheet(solved),
        "expectations.yml": _expectations(solved),
    }


# ---------------------------------------------------------------- overlay

def _nexus(socket) -> str:
    """The DT label a socket is referenced through. Board sockets are real
    nodes (their own label); carrier-exported sockets are referenced through
    the nexus the emitter synthesizes for them (Option C)."""
    return socket.nexus_label or socket.label


def _overlay(s: Solved) -> str:
    types = load_types()
    out = [f"/* {GEN}", f" * rig: {s.rig.name}  board: {s.rig.board}", " */", ""]

    out += _synth_nexus_nodes(s)

    # I2C scopes — expander is the sole author of reg + unit-address, always
    # as a matching pair (address authority rule). Mux channels (S8) are NEW
    # scopes emitted nested inside their mux device, not at the top level.
    mux_channels: dict = {}          # mux output label -> [(channel, scope path)]
    for path, (root, channel) in s.scopes.items():
        mux_channels.setdefault(root, []).append((channel, path))
    for bus_path in sorted(s.bus_label):
        if bus_path in s.scopes:                     # a mux channel — emitted nested
            continue
        devs = list(_bus_devices(s, "i2c", bus_path))
        if not devs:
            continue
        out.append(f"&{s.bus_label[bus_path]} {{")
        for inst, dev, socket in sorted(devs, key=lambda m: s.addr[(m[0].name, m[1].name)]):
            addr = s.addr[(inst.name, dev.name)]
            label = f"{inst.name}_{dev.label}"
            if label in mux_channels:                # scope-creating interposer (R26)
                out += _mux_node(s, types, inst, dev, socket, addr, mux_channels[label])
            else:
                out += _device_node(s, types, inst, dev, socket,
                                    unit=f"{addr:x}", reg=f"<{addr:#04x}>")
        out.append("};")
        out.append("")

    # SPI scopes — cs-gpios array and child reg written together (R16)
    for bus_path, entries in sorted(s.cs_gpios.items()):
        devs = list(_bus_devices(s, "spi", bus_path))
        if not devs:
            continue
        out.append(f"&{s.bus_label[bus_path]} {{")
        cs = ", ".join(f"<&{_nexus(sock)} {pos} 1 /* ACTIVE_LOW */>"
                       for sock, pos in entries)
        out.append(f"\tcs-gpios = {cs};")
        for inst, dev, socket in sorted(devs, key=lambda m: s.cs[(m[0].name, m[1].name)][0]):
            index, _pos = s.cs[(inst.name, dev.name)]
            out += _device_node(s, types, inst, dev, socket,
                                unit=str(index), reg=f"<{index}>")
        out.append("};")
        out.append("")

    # collection bindings (gpio-keys/gpio-leds, …): entries from every instance
    # aggregate under ONE node per compatible (gap #4 / R10 sibling)
    out += _collections(s, types)

    # plain non-bus device groups (not collected): per-instance container
    root_nodes = []
    for inst in sorted(s.rig.instances, key=lambda i: i.name):
        socket = s.sockets.get(inst.name)
        devs = [d for d in inst.shield.devices if d.bus is None and d.collect is None]
        if not devs or socket is None:
            continue
        root_nodes.append(f"\t{inst.name} {{")
        for dev in sorted(devs, key=lambda d: d.name):
            root_nodes += ["\t" + line
                           for line in _device_node(s, types, inst, dev, socket)]
        root_nodes.append("\t};")
    if root_nodes:
        out += ["/ {", *root_nodes, "};", ""]

    out += _controllers(s)
    return "\n".join(out)


def _controllers(s: Solved) -> list[str]:
    """Enable the timer/adc controllers a PWM/ADC claim resolved to, and NOTE
    the board-provided pin-mux each needs (Slice A: the expander names the
    pinctrl requirement; applying the SoC-specific fragment is the board's job,
    stubbed here)."""
    if not s.controllers:
        return []
    out = ["/* PWM/ADC: enable the resolved controllers; the pin-mux (pinctrl)",
           " * for each muxed pin is board-provided and must be applied —",
           " * stubbed here, see the config sheet. */"]
    for ctrl in sorted(s.controllers):
        out.append(f"&{ctrl} {{ status = \"okay\"; }};")
    out.append("")
    return out


def _sanitize(compat: str) -> str:
    return "".join(c if c.isalnum() else "_" for c in compat)


def _collections(s: Solved, types) -> list[str]:
    """Aggregate collected entries (shield,collect) by their collection
    compatible into one node each — the idiomatic gpio-keys/gpio-leds shape,
    where the compatible sits on the parent and each module is a child entry.
    (Merging into a board-provided collection of the same compatible: parked.)"""
    groups: dict[str, list] = {}
    for inst in s.rig.instances:
        socket = s.sockets.get(inst.name)
        if socket is None:
            continue
        for dev in inst.shield.devices:
            if dev.collect is not None:
                groups.setdefault(dev.collect, []).append((inst, dev, socket))
    if not groups:
        return []

    out = ["/ {"]
    for compat in sorted(groups):
        node = _sanitize(compat)
        out += [f"\t{node}: {node} {{", f'\t\tcompatible = "{compat}";']
        for inst, dev, socket in sorted(groups[compat], key=lambda m: m[0].name):
            out += ["\t" + line for line in _collection_entry(s, types, inst, dev, socket)]
        out.append("\t};")
    out += ["};", ""]
    return out


def _collection_entry(s, types, inst, dev, socket) -> list[str]:
    """One child of a collection node: the module's gpio signal. Node name and
    label are the composed <instance>_<shield label> — unique per (instance,
    device), so an instance may contribute several entries (a shield with two
    LEDs). The entry keeps its identity — aggregation, not S3 collapse."""
    lbl = f"{inst.name}_{dev.label}"
    lines = [f"\t{lbl}: {lbl} {{", f'\t\tlabel = "{lbl}";']
    # Carry through the device's passthrough properties — a collected child is
    # still a real device node and its driver may require them (e.g. the
    # gpio-keys driver mandates `zephyr,code`). Same emission as _device_node;
    # aggregation only composes the label/gpio, it must not drop the rest.
    for _pname, rendered in dev.extra_props:
        lines.append(f"\t\t{rendered}")
    ctype = types[socket.type_name]
    for ref in dev.gpio_refs:
        pos = s.positions.get((inst.name, dev.name, ref.prop), ref.position)
        flags = ref.flags ^ 0x1 if inst.invert else ref.flags
        lines.append(
            f"\t\t{ref.prop} = <&{_nexus(socket)} {pos} {flags:#x}>;"
            f"\t/* {ctype.posname(pos)}{' inverted' if inst.invert else ''} */")
    lines.append("\t};")
    return lines


def _bus_devices(s: Solved, bus: str, bus_path: str):
    for inst in s.rig.instances:
        socket = s.sockets.get(inst.name)
        if socket is None or bus not in socket.buses:
            continue
        if socket.buses[bus].path != bus_path:
            continue
        for dev in inst.shield.devices:
            if dev.bus == bus:
                yield inst, dev, socket


def _mux_node(s, types, inst, dev, socket, addr, channels) -> list[str]:
    """A scope-creating interposer device (S8 I2C mux): the device node on the
    parent bus, with one child channel bus per scope, each hosting that scope's
    modules. Per-scope address uniqueness means 0x48 can recur across channels."""
    label = f"{inst.name}_{dev.label}"
    lines = [f"\t{label}: {dev.name}@{addr:x} {{"]
    for _pname, rendered in dev.extra_props:            # compatible, …
        lines.append(f"\t\t{rendered}")
    lines += [f"\t\treg = <{addr:#04x}>;", "\t\t#address-cells = <1>;",
              "\t\t#size-cells = <0>;"]
    for channel, scope_path in sorted(channels):
        lines += [f"\t\tchannel@{channel} {{", f"\t\t\treg = <{channel}>;",
                  "\t\t\t#address-cells = <1>;", "\t\t\t#size-cells = <0>;"]
        members = sorted(_bus_devices(s, "i2c", scope_path),
                         key=lambda m: s.addr[(m[0].name, m[1].name)])
        for si, sd, ss in members:
            sa = s.addr[(si.name, sd.name)]
            lines += ["\t\t" + ln for ln in _device_node(
                s, types, si, sd, ss, unit=f"{sa:x}", reg=f"<{sa:#04x}>")]
        lines.append("\t\t};")
    lines.append("\t};")
    return lines


def _device_node(s, types, inst, dev, socket, unit=None, reg=None) -> list[str]:
    label = f"{inst.name}_{dev.label}"
    name = f"{dev.name}@{unit}" if unit is not None else dev.name
    lines = [f"\t{label}: {name} {{"]
    for _pname, rendered in dev.extra_props:
        lines.append(f"\t\t{rendered}")
    if reg is not None:
        lines.append(f"\t\treg = {reg};")
    ctype = types[socket.type_name]
    for ref in dev.gpio_refs:
        if ref.function == "gpio":
            # Conv. 3: rewrite &plug (or the routing jumper, R6) to the socket's
            # nexus — a real board node, or a synthesized carrier nexus (R19,
            # Option C). dtc chases the (multi-level) gpio-map to the pin.
            pos = s.positions.get((inst.name, dev.name, ref.prop), ref.position)
            flags = ref.flags ^ 0x1 if inst.invert else ref.flags   # bridle _inv axis
            lines.append(
                f"\t\t{ref.prop} = <&{_nexus(socket)} {pos} {flags:#x}>;"
                f"\t/* {ctype.posname(pos)}{' inverted' if inst.invert else ''} */")
        else:
            # pwm/adc (Bridge-A rewrite step 2b): SOCKET-RELATIVE, unified
            # with the gpio idiom above — dtc chases the socket's real
            # pwm-map/io-channel-map nexus (step 2a) to the controller and
            # channel; the expander no longer resolves the channel itself
            # (that special case is retired).
            #
            # PWM cells: the 2a nexus's own #pwm-cells is 2 (position,
            # period) — matching upstream atmel,sam0-tcc-pwm's flags-less
            # 2-cell convention (channel, period). pwm-map-pass-thru
            # <0x0 0xffffffff> carries exactly ONE cell through: period.
            # There is NO cell for flags — a 3rd cell here is not absorbed
            # by the map at all; dtlib parses it as the start of a BOGUS
            # trailing phandle-array element (silently a spurious null
            # entry when it happens to be 0, a hard EDTError otherwise).
            # So flags must never be emitted here; see below.
            _fn, _ctrl, _ch, period, flags, _pos = s.channels[
                (inst.name, dev.name, ref.prop)]
            pos = s.positions.get((inst.name, dev.name, ref.prop), ref.position)
            if ref.function == "pwm":
                if flags:
                    # The shield authored a nonzero PWM flag (e.g. polarity)
                    # that this 2-cell socket geometry has no cell to carry
                    # (2a design decision — flags-less, matching the
                    # target's own #pwm-cells=2). No shield in the corpus
                    # does this today; surfaced loudly rather than silently
                    # dropped, since it is real wiring information.
                    raise ValueError(
                        f"{inst.name}/{dev.name}: {ref.prop} sets PWM flags "
                        f"{flags:#x}, but the socket's pwm-map (#pwm-cells "
                        "= 2: position, period) has no cell to carry them")
                lines.append(
                    f"\t\t{ref.prop} = <&{_nexus(socket)} {pos} {period}>;"
                    f"\t/* {ctype.posname(pos)} */")
            else:  # adc
                lines.append(
                    f"\t\t{ref.prop} = <&{_nexus(socket)} {pos}>;"
                    f"\t/* {ctype.posname(pos)} */")
    # R2/T6 gap #1: every device the analyzer accepted is, by definition,
    # installed hardware -- match the legacy shield convention of an
    # explicit status = "okay" on each instantiated device (not just its
    # parent bus, which the board DT already enables unconditionally).
    lines.append('\t\tstatus = "okay";')
    # R2/T6 gap #2: an SD card on SPI needs its zephyr,sdmmc-disk child node
    # (the legacy adafruit_data_logger.overlay nests this under every
    # sdhc-spi-slot device) -- fixed, generic shape, no rig-specific data,
    # so the expander is the natural place to author it rather than
    # duplicating it in every shield that carries an SD slot.
    if dev.compatible == "zephyr,sdhc-spi-slot":
        lines += [
            "\t\tsdmmc {",
            '\t\t\tcompatible = "zephyr,sdmmc-disk";',
            '\t\t\tdisk-name = "SD";',
            '\t\t\tstatus = "okay";',
            "\t\t};",
        ]
    lines.append("\t};")
    return lines


def _synth_nexus_nodes(s: Solved) -> list[str]:
    """Emit a gpio-nexus node for each carrier-exported socket in use (R19,
    Option C), chaining to its parent's nexus. Matches hand-written nested
    overlays: a click's <&carrier_nexus pos> resolves through the carrier to
    the host board pin, keeping the routing visible in the artifact."""
    synth = {}

    def visit(sock):
        # skip board sockets (nexus_rows None) and gpio-less exposed sockets
        # (empty rows — e.g. an I2C-only mux channel, S8): nothing to route
        if sock is None or not sock.nexus_rows or sock.nexus_label in synth:
            return
        synth[sock.nexus_label] = sock
        visit(sock.parent)                 # a carrier stacked on a carrier

    for sock in s.sockets.values():
        visit(sock)
    if not synth:
        return []

    out = ["/* carrier-exported sockets, synthesized as gpio-nexus nodes */",
           "/ {"]
    for label in sorted(synth):
        sock = synth[label]
        rows = ",\n\t\t\t   ".join(
            f"<{child} 0 &{parent} {ppos} 0>"
            for child, parent, ppos in sock.nexus_rows)
        out += [f"\t{label}: {label} {{",
                "\t\t#gpio-cells = <2>;",
                # Match on the position cell only; mask the GPIO flag bits out
                # of matching and pass them through to the parent — the same
                # nexus idiom the board's own typed socket uses. Without this
                # edtlib demands an exact specifier match, so a consumer's
                # <&nexus pos GPIO_ACTIVE_LOW> would fail against the stored
                # <pos 0> row (the bug that blocked nested-carrier rigs).
                "\t\tgpio-map-mask = <0xffffffff 0xffffffc0>;",
                "\t\tgpio-map-pass-thru = <0 0x3f>;",
                f"\t\tgpio-map = {rows};",
                "\t};"]
    out += ["};", ""]
    return out


# ---------------------------------------------------------------- config sheet (R17)

def _sheet(s: Solved) -> str:
    out = [f"# Physical configuration sheet — rig `{s.rig.name}`",
           "", f"<!-- {GEN} -->", "",
           f"Board: **{s.rig.board}**", "",
           "## Socket assignment", "",
           "| instance | shield | socket |", "|---|---|---|"]
    for inst in sorted(s.rig.instances, key=lambda i: i.name):
        out.append(f"| {inst.name} | {inst.shield.name} | {inst.socket} |")

    if s.straps or s.jumpers_set:
        out += ["", "## Straps / jumpers", ""]
        for inst, strap, state, addr in sorted(
                s.straps, key=lambda t: (t[0].name, t[1].name)):
            sheet = strap.sheet_label or strap.name
            out.append(
                f"- **{inst.name}** ({inst.socket}): set **{sheet}** to state "
                f"{state} → device address {addr:#04x}")
        types = load_types()
        for inst, jmp, state, pos in sorted(
                s.jumpers_set, key=lambda t: (t[0].name, t[1].name)):
            sheet = jmp.sheet_label or jmp.name
            posname = types[s.sockets[inst.name].type_name].posname(pos)
            out.append(
                f"- **{inst.name}** ({inst.socket}): set **{sheet}** to state "
                f"{state} → routed to pin {posname}")

    if s.channels:
        types = load_types()
        out += ["", "## PWM / analog pin-mux (board-provided pinctrl)", "",
                "The expander enables these controllers; the SoC pin-mux for "
                "each pin is board-provided and must be applied (stubbed):", ""]
        for (inst, dev, prop), (fn, ctrl, ch, _p, _f, pos) in sorted(s.channels.items()):
            socket = s.sockets[inst]
            posname = types[socket.type_name].posname(pos)
            out.append(f"- {inst}/{dev} ({socket.label} {posname}) → "
                       f"{fn.upper()} {ctrl} ch{ch}: mux the pin to the controller")

    if s.rig.wires:
        out += ["", "## Wires", ""]
        for w in s.rig.wires:
            route = ("ad-hoc jumper wire (in no connector)"
                     if w.route == "adhoc" else f"via header position {w.route}")
            out.append(
                f"- connect **{w.frm.instance.name}.{w.frm.node}** → "
                f"**{w.to.instance.name}.{w.to.node}** — {route}")

    if s.cs:
        types = load_types()
        out += ["", "## Chip-selects", ""]
        for (inst_name, dev_name), (index, pos) in sorted(s.cs.items()):
            socket = s.sockets[inst_name]
            posname = types[socket.type_name].posname(pos)
            mapping = socket.gpio_map.get(pos)
            soc = f" → SoC {mapping[0]} pin {mapping[1]}" if mapping else ""
            out.append(f"- {inst_name}/{dev_name}: CS index {index}, {posname}{soc}")
    return "\n".join(out) + "\n"


# ---------------------------------------------------------------- expectations (A6)

def _expectations(s: Solved) -> str:
    out = [f"# {GEN}",
           "# test expectations stub (A6): what a runtime harness must observe",
           f"rig: {s.rig.name}", f"board: {s.rig.board}", "expect:"]
    for (inst, dev), addr in sorted(s.addr.items()):
        socket = s.sockets[inst]
        out.append(f"  - {{instance: {inst}, device: {dev}, "
                   f"bus: {socket.buses['i2c'].label}, address: {addr:#04x}, "
                   "check: probe}")
    for (inst, dev), (index, _pos) in sorted(s.cs.items()):
        socket = s.sockets[inst]
        out.append(f"  - {{instance: {inst}, device: {dev}, "
                   f"bus: {socket.buses['spi'].label}, cs-index: {index}, "
                   "check: probe}")
    for w in s.rig.wires:
        out.append(f"  - {{signal: {w.frm.instance.name}.{w.frm.node} -> "
                   f"{w.to.instance.name}.{w.to.node}, check: manual}}")
    return "\n".join(out) + "\n"
