# generated by rigc — consumed by cmake/dts.cmake
set(RIG_NAME "grove_sens_pinned")
set(RIG_BOARD "m5stack_nanoc6/esp32c6/hpcore/rig")
set(RIG_SHIELDS "grove_sens_bme280")
set(RIG_DEPENDS "<REPO_ROOT>/boards/extend/m5stack/m5stack_nanoc6/m5stack_nanoc6_esp32c6_hpcore_rig.dts;<REPO_ROOT>/boards/rigs/grove_sens_pinned/grove_sens_pinned.yml;<REPO_ROOT>/boards/rigs/grove_sens_pinned/rig.yml;<REPO_ROOT>/boards/shields/grove_sens/grove_sens_bme280.shield;<REPO_ROOT>/boards/shields/grove_sens/shield.yml;<REPO_ROOT>/dts/bindings/connectors/arduino-r3.yaml;<REPO_ROOT>/dts/bindings/connectors/grove.yaml;<REPO_ROOT>/dts/bindings/connectors/i2c-port.yaml;<REPO_ROOT>/dts/bindings/connectors/mikrobus.yaml;<REPO_ROOT>/include/dt-bindings/connector/arduino-r3.h;<REPO_ROOT>/include/dt-bindings/connector/grove.h;<REPO_ROOT>/include/dt-bindings/connector/i2c-port.h;<REPO_ROOT>/include/dt-bindings/connector/mikrobus.h")
