# generated by rigc — consumed by btr-shields/cmake/dts.cmake
set(RIG_NAME "shield-uart-subset")
set(RIG_BOARD "frdm_k64f/mk64f12/rig")
set(RIG_SHIELDS "uart_probe")
set(RIG_VARIANT "frdm")
set(RIG_DEPENDS "<REPO_ROOT>/boards/extend/nxp/frdm_k64f/frdm_k64f_mk64f12_rig.dts;<REPO_ROOT>/dts/bindings/connectors/arduino-r3.yaml;<REPO_ROOT>/dts/bindings/connectors/grove.yaml;<REPO_ROOT>/dts/bindings/connectors/i2c-port.yaml;<REPO_ROOT>/dts/bindings/connectors/mikrobus.yaml;<REPO_ROOT>/include/dt-bindings/connector/arduino-r3.h;<REPO_ROOT>/include/dt-bindings/connector/grove.h;<REPO_ROOT>/include/dt-bindings/connector/i2c-port.h;<REPO_ROOT>/include/dt-bindings/connector/mikrobus.h;<REPO_ROOT>/scripts/rigc/tests/fixtures/boards/rigs/shield-uart-subset/rig.yml;<REPO_ROOT>/scripts/rigc/tests/fixtures/boards/rigs/shield-uart-subset/shield-uart-subset.yml;<REPO_ROOT>/scripts/rigc/tests/fixtures/boards/rigs/shield-uart-subset/shields/uart_probe/uart_probe.shield")
