# generated by rigc — consumed by cmake/dts.cmake
set(RIG_NAME "ard_datalogger")
set(RIG_BOARD "frdm_k64f/mk64f12/rig")
set(RIG_SHIELDS "adafruit_data_logger")
set(RIG_DEPENDS "<REPO_ROOT>/boards/extend/nxp/frdm_k64f/frdm_k64f_mk64f12_rig.dts;<REPO_ROOT>/boards/rigs/ard_datalogger/ard_datalogger.yml;<REPO_ROOT>/boards/rigs/ard_datalogger/rig.yml;<REPO_ROOT>/boards/shields/adafruit_data_logger/adafruit_data_logger.shield;<REPO_ROOT>/boards/shields/adafruit_data_logger/shield.yml;<REPO_ROOT>/dts/bindings/connectors/arduino-r3.yaml;<REPO_ROOT>/dts/bindings/connectors/grove.yaml;<REPO_ROOT>/dts/bindings/connectors/i2c-port.yaml;<REPO_ROOT>/dts/bindings/connectors/mikrobus.yaml;<REPO_ROOT>/include/dt-bindings/connector/arduino-r3.h;<REPO_ROOT>/include/dt-bindings/connector/grove.h;<REPO_ROOT>/include/dt-bindings/connector/i2c-port.h;<REPO_ROOT>/include/dt-bindings/connector/mikrobus.h")
