"""Unit: compare -- context.cmake's structural comparator, replacing a
byte comparison with an assertion over its actual contract (a key -> value
mapping, RIG_DEPENDS a SET, RIG_SHIELDS an ORDERED list). See
scripts/rigc/tests/compare.py's own docstring for the contract itself.

Most cases below are deliberate NEGATIVE CONTROLS: a mutation
compare_context_cmake must still reject. A comparator nobody has proven
can still fail is a tautological check at suite scale -- the same defect
class the reject-corpus review round already caught once in a unit test
(rigc-r5-brief.md's review notes), applied here to the comparator itself.
"""
from __future__ import annotations

import textwrap

import pytest

from rigc.tests.compare import (
    ContextCmakeParseError,
    compare_context_cmake,
    parse_context_cmake,
    split_dependency_set,
)

GOLDEN = textwrap.dedent("""\
    # generated by rigc — consumed by btr-shields/cmake/dts.cmake
    set(RIG_NAME "nucleo_datalogger")
    set(RIG_BOARD "nucleo_f401re/stm32f401xe/rig")
    set(RIG_SHIELDS "adafruit_data_logger;i2c_sensor")
    set(RIG_REVISION "1")
    set(RIG_DEPENDS "/a/board.dts;/a/rig.yml;/a/shield.shield")
    """)


def test_parses_set_lines_into_a_mapping() -> None:
    parsed = parse_context_cmake(GOLDEN)
    assert parsed["RIG_NAME"] == "nucleo_datalogger"
    assert parsed["RIG_BOARD"] == "nucleo_f401re/stm32f401xe/rig"
    assert parsed["RIG_SHIELDS"] == "adafruit_data_logger;i2c_sensor"
    assert parsed["RIG_REVISION"] == "1"


def test_comment_lines_are_ignored() -> None:
    parsed = parse_context_cmake(GOLDEN)
    assert set(parsed) == {
        "RIG_NAME", "RIG_BOARD", "RIG_SHIELDS", "RIG_REVISION",
        "RIG_DEPENDS"}


def test_unparseable_line_raises_on_parse() -> None:
    with pytest.raises(ContextCmakeParseError):
        parse_context_cmake("this is not cmake at all\n")


def test_split_dependency_set_undoes_cmake_list_escaping() -> None:
    # "/a;weird.dts" was escaped by emitter/context.py's
    # _cmake_list_escape to "/a\;weird.dts" before joining -- the
    # backslash-semicolon must NOT be read as the element delimiter.
    raw = r"/a\;weird.dts;/b/plain.yml"
    assert split_dependency_set(raw) == frozenset(
        {"/a;weird.dts", "/b/plain.yml"})


def test_identical_text_compares_equal() -> None:
    assert compare_context_cmake(GOLDEN, GOLDEN) is None


# --- negative controls (cutover-brief.md Sec 3) ------------------------


def test_reordering_rig_depends_is_accepted() -> None:
    reordered = GOLDEN.replace(
        '"/a/board.dts;/a/rig.yml;/a/shield.shield"',
        '"/a/shield.shield;/a/board.dts;/a/rig.yml"')
    assert compare_context_cmake(GOLDEN, reordered) is None


def test_dropping_a_rig_depends_entry_is_rejected() -> None:
    dropped = GOLDEN.replace(
        '"/a/board.dts;/a/rig.yml;/a/shield.shield"',
        '"/a/board.dts;/a/rig.yml"')
    mismatch = compare_context_cmake(GOLDEN, dropped)
    assert mismatch is not None
    assert "RIG_DEPENDS" in mismatch
    assert "missing" in mismatch
    assert "/a/shield.shield" in mismatch


def test_adding_an_unexpected_rig_depends_entry_is_rejected() -> None:
    added = GOLDEN.replace(
        '"/a/board.dts;/a/rig.yml;/a/shield.shield"',
        '"/a/board.dts;/a/rig.yml;/a/shield.shield;/a/extra.h"')
    mismatch = compare_context_cmake(GOLDEN, added)
    assert mismatch is not None
    assert "RIG_DEPENDS" in mismatch
    assert "unexpected" in mismatch
    assert "/a/extra.h" in mismatch


def test_changing_rig_board_value_is_rejected() -> None:
    changed = GOLDEN.replace(
        'set(RIG_BOARD "nucleo_f401re/stm32f401xe/rig")',
        'set(RIG_BOARD "frdm_k64f/mk64f12/rig")')
    mismatch = compare_context_cmake(GOLDEN, changed)
    assert mismatch is not None
    assert "RIG_BOARD" in mismatch


def test_reordering_rig_shields_is_rejected() -> None:
    """RIG_SHIELDS is documented as distinct-in-rig-order and dts.cmake
    iterates it -- unlike RIG_DEPENDS, its order IS the contract."""
    reordered = GOLDEN.replace(
        'set(RIG_SHIELDS "adafruit_data_logger;i2c_sensor")',
        'set(RIG_SHIELDS "i2c_sensor;adafruit_data_logger")')
    mismatch = compare_context_cmake(GOLDEN, reordered)
    assert mismatch is not None
    assert "RIG_SHIELDS" in mismatch


def test_omitting_rig_revision_entirely_is_rejected() -> None:
    """The "no declaration, no artifact" rule (emitter/context.py) makes
    RIG_REVISION's absence meaningful -- a golden that carries it must
    reject an actual run that dropped it, not treat the axis as
    unconstrained."""
    without_revision = "\n".join(
        line for line in GOLDEN.splitlines()
        if not line.startswith('set(RIG_REVISION')) + "\n"
    mismatch = compare_context_cmake(GOLDEN, without_revision)
    assert mismatch is not None
    assert "RIG_REVISION" in mismatch
    assert "absent" in mismatch


def test_a_differing_banner_comment_is_accepted() -> None:
    """Comment lines carry no contract for this artifact -- the banner is
    the provenance leak this comparator exists to stop mattering."""
    different_banner = GOLDEN.replace(
        "# generated by rigc — consumed by btr-shields/cmake/dts.cmake",
        "# generated by something else entirely, worded differently")
    assert compare_context_cmake(GOLDEN, different_banner) is None


def test_unparseable_actual_is_a_reported_mismatch_not_an_exception() -> None:
    mismatch = compare_context_cmake(GOLDEN, "not cmake at all\n")
    assert mismatch is not None
    assert "failed to parse" in mismatch


def test_unparseable_golden_is_a_reported_mismatch_not_an_exception() -> None:
    mismatch = compare_context_cmake("not cmake at all\n", GOLDEN)
    assert mismatch is not None
    assert "failed to parse" in mismatch
