"""Unit: emitter/expectations -- expectations.yml (rigc-r5-brief.md Sec
4). Same `solved.wires`-never-`rig.wires` contract as sheet.py, pinned
here from the OTHER angle: since a wire's rendered line carries no route
text (only the endpoint pair), the trap is proven by using two DIFFERENT
wires -- one on `rig.wires` only, one on `solved.wires` only -- and
asserting the emitted signal line names the SOLVED one.
"""
from __future__ import annotations

from rigc.analyzer import Solved
from rigc.diag import SourceRef
from rigc.emitter.expectations import render_expectations
from rigc.model import Rig, Wire, WireEnd

_SRC = SourceRef("f.yml", 1, "k")


def test_wire_signals_come_from_solved_wires_not_rig_wires() -> None:
    rig_only = Wire(frm=WireEnd(instance_name="a", node="x", src=_SRC),
                    to=WireEnd(instance_name="b", node="y", src=_SRC),
                    route="adhoc", src=_SRC)
    solved_only = Wire(frm=WireEnd(instance_name="c", node="p", src=_SRC),
                       to=WireEnd(instance_name="d", node="q", src=_SRC),
                       route="adhoc", src=_SRC)

    rig = Rig(name="r", instances=[], wires=[rig_only])
    s = Solved(wires=[solved_only])

    text = render_expectations(rig, s)

    assert "c.p -> d.q" in text
    assert "a.x -> b.y" not in text


def test_addr_and_cs_entries_are_sorted_and_carry_the_probe_check() -> None:
    from rigc.model import BoardSocket, BusRef

    rig = Rig(name="r", board="b", instances=[])
    s = Solved(
        sockets={"i1": BoardSocket(label="s1", path="/s1", type_name="t",
                                   gpio_map={}, buses={
                                       "i2c": BusRef("i2c1", "/i2c1"),
                                       "spi": BusRef("spi1", "/spi1")},
                                   cs_pool=None)},
        addr={("i1", "sensor"): 0x50},
        cs={("i1", "flash"): (0, 5)})

    text = render_expectations(rig, s)

    assert ("instance: i1, device: sensor, bus: i2c1, address: 0x50, "
           "check: probe") in text
    assert ("instance: i1, device: flash, bus: spi1, cs-index: 0, "
           "check: probe") in text


def test_banner_and_rig_identity_lines() -> None:
    rig = Rig(name="my-rig", board="my-board", instances=[])
    s = Solved()

    text = render_expectations(rig, s)

    assert "rig: my-rig" in text
    assert "board: my-board" in text
    assert text.startswith("# generated by rigc")
