# generated by rigc — consumed by cmake/dts.cmake
set(RIG_NAME "quail_can_span")
set(RIG_BOARD "mikroe_quail/stm32f427xx/rig")
set(RIG_SHIELDS "can_span_click")
set(RIG_DEPENDS "<REPO_ROOT>/boards/extend/mikroe/quail/mikroe_quail_stm32f427xx_rig.dts;<REPO_ROOT>/boards/rigs/quail_can_span/quail_can_span.yml;<REPO_ROOT>/boards/rigs/quail_can_span/rig.yml;<REPO_ROOT>/boards/shields/can_span_click/can_span_click.shield;<REPO_ROOT>/boards/shields/can_span_click/shield.yml;<REPO_ROOT>/dts/bindings/connectors/arduino-r3.yaml;<REPO_ROOT>/dts/bindings/connectors/grove.yaml;<REPO_ROOT>/dts/bindings/connectors/i2c-port.yaml;<REPO_ROOT>/dts/bindings/connectors/mikrobus.yaml;<REPO_ROOT>/include/dt-bindings/connector/arduino-r3.h;<REPO_ROOT>/include/dt-bindings/connector/grove.h;<REPO_ROOT>/include/dt-bindings/connector/i2c-port.h;<REPO_ROOT>/include/dt-bindings/connector/mikrobus.h")
