# generated by rigc — consumed by cmake/dts.cmake
set(RIG_NAME "nucleo_mux_farm")
set(RIG_BOARD "nucleo_f401re/stm32f401xe/rig")
set(RIG_SHIELDS "i2c_mux;i2c_sensor")
set(RIG_SHIELD_REVISIONS "i2c_sensor@1")
set(RIG_DEPENDS "<REPO_ROOT>/boards/extend/st/nucleo_f401re/nucleo_f401re_stm32f401xe_rig.dts;<REPO_ROOT>/boards/rigs/nucleo_mux_farm/nucleo_mux_farm.yml;<REPO_ROOT>/boards/rigs/nucleo_mux_farm/rig.yml;<REPO_ROOT>/boards/shields/i2c_mux/i2c_mux.shield;<REPO_ROOT>/boards/shields/i2c_mux/shield.yml;<REPO_ROOT>/boards/shields/i2c_sensor/i2c_sensor.shield;<REPO_ROOT>/boards/shields/i2c_sensor/shield.yml;<REPO_ROOT>/dts/bindings/connectors/arduino-r3.yaml;<REPO_ROOT>/dts/bindings/connectors/grove.yaml;<REPO_ROOT>/dts/bindings/connectors/i2c-port.yaml;<REPO_ROOT>/dts/bindings/connectors/mikrobus.yaml;<REPO_ROOT>/include/dt-bindings/connector/arduino-r3.h;<REPO_ROOT>/include/dt-bindings/connector/grove.h;<REPO_ROOT>/include/dt-bindings/connector/i2c-port.h;<REPO_ROOT>/include/dt-bindings/connector/mikrobus.h")
