"""The EMITTER (architecture.md): Solved rig -> the projection triple,
split by visibility (ontology Sec 3):

  MCU-visible-static   -> .overlay        (joins the unchanged Zephyr build)
  human-realized       -> config sheet    (markdown)
  runtime-discoverable -> expectations    (YAML stub, A6)

Ported whole from rigexp/emitter.py (rigc-r5-brief.md Sec 1) -- pure
rendering under the strong contract: never decides anything, never fails
on an analyzer-accepted rig. Deterministic: all output sorted by stable
keys, independent of rig-file declaration order (R7/R18).

Split into `overlay.py` (nexus synthesis, I2C/SPI scopes, collections,
plain groups, controllers, the device-node renderer), `sheet.py`
(config-sheet.md, including the params table's token resolution),
`expectations.py`, and this module (composing `emit()` and the ONE
writer). `context.py` renders context.cmake as its own value function --
kept out of `emit()` to preserve the blueprint's own semantic boundary
between rig artifacts and build glue (rigc-r5-brief.md Sec 2).

**Artifacts are `{filename: bytes}`, explicit UTF-8** (ratified ruling
4): `config-sheet.md` carries non-ASCII punctuation (arrows, em dashes),
so the encoding is a real decision, not a formality. The sub-renderers
return `str` (readable in unit tests); this module is the one place that
encodes them into the bytes-valued mapping cli.py hands to `write()`.

**Read `solved.wires`, never `rig.wires`** (rigc-r5-brief.md Sec 1): the
loader's `rig.wires` carries the RAW `via <name>` route string;
`analyzer.wires.check_wires` returns NEW Wire values with the route
resolved to a connector-type position INDEX, held only on `Solved.wires`.
Every renderer below takes `solved` and never reaches back through
`rig.wires`.
"""
from __future__ import annotations

import logging
import os
from typing import Dict, List, Optional

log = logging.getLogger(__name__)

#: The shared provenance banner every rig-gen.* artifact carries (three
#: comment forms: /* */ in the overlay and includes file, <!-- --> in the
#: config sheet, # in expectations.yml). Read by overlay.py/sheet.py/
#: expectations.py below; defined here (assigned before those submodules
#: are imported) so this one package-level value is the single source
#: instead of a literal repeated per file.
GEN = "generated by rigc — do not edit; the rig file is the source of truth (R3)"

from ..analyzer import Solved
from ..model import ConnectorType, Rig
from .expectations import render_expectations
from .overlay import render_overlay
from .sheet import render_sheet

__all__ = ["emit", "write_artifacts"]


def emit(rig: Rig, solved: Solved, types: Dict[str, ConnectorType], workdir: str,
         include_dirs: Optional[List[str]] = None) -> Dict[str, bytes]:
    """Compute the rig artifacts (never context.cmake -- that is
    `context.render`, a build-glue concern kept out of this function by
    design) as a `{filename: bytes}` mapping. `include_dirs` is the cpp
    -I search list threaded into the config sheet's own token resolution
    (`dtsio.resolve_token`, via `sheet._params_table`) -- the same list a
    caller threads as --include-dir everywhere else; None reproduces the
    ZEPHYR_INC/MODULE_INC-only search, unchanged.

    Returns a fresh mapping the caller owns; `rig`/`solved`/`types` are
    read-only. `rig-gen-includes.dtsi` appears iff `rig.dt_includes` is
    non-empty (the common corpus case gets no extra artifact and no
    include line, zero churn); `rig-gen.conf` never appears (no
    corpus/fixture rig produces per-instance Kconfig fragments yet);
    `expectations.yml` always appears, though nothing gates its content
    (test_emitted_corpus.py's own docstring)."""
    log.info("emit(): rig '%s'", rig.name)
    outputs = {
        "rig-gen.overlay": render_overlay(rig, solved, types).encode("utf-8"),
        "config-sheet.md": render_sheet(rig, solved, types, workdir,
                                        include_dirs).encode("utf-8"),
        "expectations.yml": render_expectations(rig, solved).encode("utf-8"),
    }
    if rig.dt_includes:
        outputs["rig-gen-includes.dtsi"] = _render_includes_dtsi(
            rig.dt_includes).encode("utf-8")
    for fname, content in outputs.items():
        log.debug("emit(): rendered %s (%d bytes)", fname, len(content))
    return outputs


def _render_includes_dtsi(dt_includes: List[str]) -> str:
    """The fourth generated artifact: nothing but the rig's declared
    #include lines. rig-gen.overlay pulls this in via a QUOTED include at
    the top of the file -- quoted-include resolution against the
    including file's own directory means both files can simply sit
    side-by-side in <build>/rig/ with no -I plumbing, no
    EXTRA_DTC_OVERLAY_FILE entry, no ordering constraint in cmake, and no
    build_info key: the dependency is visible in the file that has it."""
    out = [f"/* {GEN} */", ""]
    out += [f"#include <{header}>" for header in dt_includes]
    out.append("")
    return "\n".join(out)


def write_artifacts(out_dir: str, artifacts: Dict[str, bytes]) -> None:
    """The ONE shell that performs every artifact write, binary mode --
    the IO-at-the-edges boundary (mission brief Sec 6): every renderer
    above and `context.render` computes bytes as a pure value, and this
    is the only place any of them touch a filesystem. Creates out_dir if
    needed (a caller passing a fresh --out-dir is the common case, not an
    error).

    artifacts is read-only; writes each mapping entry as out_dir/<name>,
    returns nothing."""
    log.info("write_artifacts(): writing %d file(s) to %s", len(artifacts), out_dir)
    os.makedirs(out_dir, exist_ok=True)
    for fname, content in artifacts.items():
        path = os.path.join(out_dir, fname)
        with open(path, "wb") as f:
            f.write(content)
        log.info("write_artifacts(): wrote %s (%d bytes)", path, len(content))
