# generated by rigc — consumed by btr-shields/cmake/dts.cmake
set(RIG_NAME "lotus_pwm")
set(RIG_BOARD "seeeduino_lotus/samd21g18a/rig")
set(RIG_SHIELDS "grove_servo;grove_light")
set(RIG_DEPENDS "<REPO_ROOT>/boards/extend/seeed/seeeduino_lotus/seeeduino_lotus_samd21g18a_rig.dts;<REPO_ROOT>/boards/rigs/lotus_pwm/lotus_pwm.yml;<REPO_ROOT>/boards/rigs/lotus_pwm/rig.yml;<REPO_ROOT>/boards/shields/grove_light/grove_light.shield;<REPO_ROOT>/boards/shields/grove_light/shield.yml;<REPO_ROOT>/boards/shields/grove_servo/grove_servo.shield;<REPO_ROOT>/boards/shields/grove_servo/shield.yml;<REPO_ROOT>/dts/bindings/connectors/arduino-r3.yaml;<REPO_ROOT>/dts/bindings/connectors/grove.yaml;<REPO_ROOT>/dts/bindings/connectors/i2c-port.yaml;<REPO_ROOT>/dts/bindings/connectors/mikrobus.yaml;<REPO_ROOT>/include/dt-bindings/connector/arduino-r3.h;<REPO_ROOT>/include/dt-bindings/connector/grove.h;<REPO_ROOT>/include/dt-bindings/connector/i2c-port.h;<REPO_ROOT>/include/dt-bindings/connector/mikrobus.h")
