# generated by rigexp — consumed by btr-shields/cmake/dts.cmake
set(RIG_NAME "shield_rev_family")
set(RIG_BOARD "nucleo_f401re/stm32f401xe/rig")
set(RIG_SHIELDS "i2c_mux;i2c_sensor")
set(RIG_SHIELD_REVISIONS "i2c_sensor@2")
set(RIG_REVISION "2")
set(RIG_DEPENDS "<REPO_ROOT>/boards/extend/st/nucleo_f401re/nucleo_f401re_stm32f401xe_rig.dts;<REPO_ROOT>/boards/rigs/shield_rev_family/rig.yml;<REPO_ROOT>/boards/rigs/shield_rev_family/shield_rev_family.yml;<REPO_ROOT>/boards/rigs/shield_rev_family/shield_rev_family_2.yml;<REPO_ROOT>/boards/shields/i2c_mux/i2c_mux.shield;<REPO_ROOT>/boards/shields/i2c_mux/shield.yml;<REPO_ROOT>/boards/shields/i2c_sensor/i2c_sensor.shield;<REPO_ROOT>/boards/shields/i2c_sensor/i2c_sensor_2.shield;<REPO_ROOT>/boards/shields/i2c_sensor/shield.yml;<REPO_ROOT>/dts/bindings/connectors/arduino-r3.yaml;<REPO_ROOT>/dts/bindings/connectors/grove.yaml;<REPO_ROOT>/dts/bindings/connectors/i2c-port.yaml;<REPO_ROOT>/dts/bindings/connectors/mikrobus.yaml;<REPO_ROOT>/include/dt-bindings/connector/arduino-r3.h;<REPO_ROOT>/include/dt-bindings/connector/grove.h;<REPO_ROOT>/include/dt-bindings/connector/i2c-port.h;<REPO_ROOT>/include/dt-bindings/connector/mikrobus.h")
