# generated by rigc — consumed by cmake/dts.cmake
set(RIG_NAME "frdm_eth_nest")
set(RIG_BOARD "frdm_k64f/mk64f12/rig")
set(RIG_SHIELDS "arduino_uno_click;eth_click")
set(RIG_DEPENDS "<REPO_ROOT>/boards/extend/nxp/frdm_k64f/frdm_k64f_mk64f12_rig.dts;<REPO_ROOT>/boards/rigs/frdm_eth_nest/frdm_eth_nest.yml;<REPO_ROOT>/boards/rigs/frdm_eth_nest/rig.yml;<REPO_ROOT>/boards/shields/arduino_uno_click/arduino_uno_click.shield;<REPO_ROOT>/boards/shields/arduino_uno_click/shield.yml;<REPO_ROOT>/boards/shields/eth_click/eth_click.shield;<REPO_ROOT>/boards/shields/eth_click/shield.yml;<REPO_ROOT>/dts/bindings/connectors/arduino-r3.yaml;<REPO_ROOT>/dts/bindings/connectors/grove.yaml;<REPO_ROOT>/dts/bindings/connectors/i2c-port.yaml;<REPO_ROOT>/dts/bindings/connectors/mikrobus.yaml;<REPO_ROOT>/include/dt-bindings/connector/arduino-r3.h;<REPO_ROOT>/include/dt-bindings/connector/grove.h;<REPO_ROOT>/include/dt-bindings/connector/i2c-port.h;<REPO_ROOT>/include/dt-bindings/connector/mikrobus.h")
